[package]
name = "fighter_simulator"
version = "0.1.0"
authors = ["Steven Malis <smmalis37@gmail.com>"]

[dependencies]
rand = "0.5.5"
enum-map = "0.4.1"
rayon = "1.0.2"

[profile.release]
lto = "thin"
