[package]
name = "fighter_simulator"
version = "0.1.0"
authors = ["Steven Malis <smmalis37@gmail.com>"]
edition = "2018"

[dependencies]
rand = { version = "0.8.0", features = ["small_rng"] }
enum-map = "1.1"
rayon = "1.5.0"
arrayvec = "0.7"

[profile.release]
lto = "thin"
